# Generated by Django 5.2.7 on 2025-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartPage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxesandcharges",
            name="min_amount_for_free_delivery",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
