# Generated by Django 5.2.5 on 2025-10-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0005_address_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="is_available_for_cod",
            field=models.BooleanField(default=True),
        ),
    ]
