# Generated by Django 5.2.5 on 2025-10-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0006_cartitem_is_available_for_cod"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxesAndCharges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "delivery_charges",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
            ],
        ),
    ]
