# Generated by Django 5.2.6 on 2025-09-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
