# Generated by Django 5.2.6 on 2025-09-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='S', help_text='Comma-separated sizes, e.g. S,M,L,XL', max_length=200),
        ),
    ]
