# Generated by Django 5.2.5 on 2025-09-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("color", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
