# Generated by Django 5.2.5 on 2025-12-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartPage", "0003_alter_cartitem_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
